-- Human immune-related gene expression database seeded from HPA and UniProt
-- Data sources: Human Protein Atlas rna_immune_cell.tsv and UniProtKB REST/FASTA records
CREATE DATABASE IF NOT EXISTS bio_demo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE bio_demo;

DROP VIEW IF EXISTS view_source_summary;
DROP VIEW IF EXISTS view_gene_class_summary;
DROP VIEW IF EXISTS view_species_summary;
DROP VIEW IF EXISTS view_dataset_counts;
DROP TABLE IF EXISTS expression;
DROP TABLE IF EXISTS import_logs;
DROP TABLE IF EXISTS samples;
DROP TABLE IF EXISTS genes;

CREATE TABLE genes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    gene_symbol VARCHAR(100) NOT NULL UNIQUE,
    ensembl_id VARCHAR(100) UNIQUE,
    uniprot_id VARCHAR(100),
    protein_name TEXT,
    species VARCHAR(255) NOT NULL,
    gene_class VARCHAR(255),
    description TEXT,
    sequence_type VARCHAR(50) DEFAULT 'protein',
    sequence MEDIUMTEXT,
    source_database VARCHAR(255),
    source_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE samples (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sample_name VARCHAR(255) NOT NULL UNIQUE,
    tissue VARCHAR(255),
    condition_name VARCHAR(255),
    species VARCHAR(255) NOT NULL,
    source_database VARCHAR(255),
    description TEXT
);

CREATE TABLE expression (
    id INT AUTO_INCREMENT PRIMARY KEY,
    gene_id INT NOT NULL,
    sample_id INT NOT NULL,
    expression_value DOUBLE NOT NULL,
    expression_unit VARCHAR(50) DEFAULT 'TPM',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_gene_sample (gene_id, sample_id),
    CONSTRAINT fk_expression_gene FOREIGN KEY (gene_id) REFERENCES genes(id) ON DELETE CASCADE,
    CONSTRAINT fk_expression_sample FOREIGN KEY (sample_id) REFERENCES samples(id) ON DELETE CASCADE
);

CREATE TABLE import_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    import_type VARCHAR(100) NOT NULL,
    records_inserted INT NOT NULL DEFAULT 0,
    imported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    notes TEXT
);

INSERT INTO genes (gene_symbol, ensembl_id, uniprot_id, protein_name, species, gene_class, description, sequence_type, sequence, source_database, source_url) VALUES
('IL6', 'ENSG00000136244', 'P05231', 'Interleukin-6 (IL-6) (B-cell stimulatory factor 2) (BSF-2) (CTL differentiation factor) (CDF) (Hybridoma growth factor) (Interferon beta-2) (IFN-beta-2)', 'Homo sapiens', 'cytokine', 'Human immune-related protein annotated in UniProt; class: cytokine.', 'protein', 'MNSFSTSAFGPVAFSLGLLLVLPAAFPAPVPPGEDSKDVAAPHRQPLTSSERIDKQIRYILDGISALRKETCNKSNMCESSKEALAENNLNLPKMAEKDGCFQSGFNEETCLVKIITGLLEFEVYLEYLQNRFESSEEQARAVQMSTKVLIQFLQKKAKNLDAITTPDPTTNASLLTKLQAQNQWLQDMTTHLILRSFKEFLQSSLRALRQM', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/P05231/entry'),
('IL1B', 'ENSG00000125538', 'P01584', 'Interleukin-1 beta (IL-1 beta) (Catabolin)', 'Homo sapiens', 'cytokine', 'Human immune-related protein annotated in UniProt; class: cytokine.', 'protein', 'MAEVPELASEMMAYYSGNEDDLFFEADGPKQMKCSFQDLDLCPLDGGIQLRISDHHYSKGFRQAASVVVAMDKLRKMLVPCPQTFQENDLSTFFPFIFEEEPIFFDTWDNEAYVHDAPVRSLNCTLRDSQQKSLVMSGPYELKALHLQGQDMEQQVVFSMSFVQGEESNDKIPVALGLKEKNLYLSCVLKDDKPTLQLESVDPKNYPKKKMEKRFVFNKIEINNKLEFESAQFPNWYISTSQAENMPVFLGGTKGGQDITDFTMQFVSS', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/P01584/entry'),
('TNF', 'ENSG00000232810', 'P01375', 'Tumor necrosis factor (Cachectin) (TNF-alpha) (Tumor necrosis factor ligand superfamily member 2) (TNF-a) [Cleaved into: Tumor necrosis factor, membrane form (N-terminal fragment) (NTF); Intracellular domain 1 (ICD1); Intracellular domain 2 (ICD2); C-domain 1; C-domain 2; Tumor necrosis factor, soluble form]', 'Homo sapiens', 'cytokine', 'Human immune-related protein annotated in UniProt; class: cytokine.', 'protein', 'MSTESMIRDVELAEEALPKKTGGPQGSRRCLFLSLFSFLIVAGATTLFCLLHFGVIGPQREEFPRDLSLISPLAQAVRSSSRTPSDKPVAHVVANPQAEGQLQWLNRRANALLANGVELRDNQLVVPSEGLYLIYSQVLFKGQGCPSTHVLLTHTISRIAVSYQTKVNLLSAIKSPCQRETPEGAEAKPWYEPIYLGGVFQLEKGDRLSAEINRPDYLDFAESGQVYFGIIAL', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/P01375/entry'),
('IFNG', 'ENSG00000111537', 'P01579', 'Interferon gamma (IFN-gamma) (Immune interferon)', 'Homo sapiens', 'cytokine', 'Human immune-related protein annotated in UniProt; class: cytokine.', 'protein', 'MKYTSYILAFQLCIVLGSLGCYCQDPYVKEAENLKKYFNAGHSDVADNGTLFLGILKNWKEESDRKIMQSQIVSFYFKLFKNFKDDQSIQKSVETIKEDMNVKFFNSNKKKRDDFEKLTNYSVTDLNVQRKAIHELIQVMAELSPAAKTGKRKRSQMLFRGRRASQ', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/P01579/entry'),
('IL10', 'ENSG00000136634', 'P22301', 'Interleukin-10 (IL-10) (Cytokine synthesis inhibitory factor) (CSIF)', 'Homo sapiens', 'cytokine', 'Human immune-related protein annotated in UniProt; class: cytokine.', 'protein', 'MHSSALLCCLVLLTGVRASPGQGTQSENSCTHFPGNLPNMLRDLRDAFSRVKTFFQMKDQLDNLLLKESLLEDFKGYLGCQALSEMIQFYLEEVMPQAENQDPDIKAHVNSLGENLKTLRLRLRRCHRFLPCENKSKAVEQVKNAFNKLQEKGIYKAMSEFDIFINYIEAYMTMKIRN', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/P22301/entry'),
('CXCL8', 'ENSG00000169429', 'P10145', 'Interleukin-8 (IL-8) (C-X-C motif chemokine 8) (Chemokine (C-X-C motif) ligand 8) (Emoctakin) (Granulocyte chemotactic protein 1) (GCP-1) (Monocyte-derived neutrophil chemotactic factor) (MDNCF) (Monocyte-derived neutrophil-activating peptide) (MONAP) (Neutrophil-activating protein 1) (NAP-1) (Protein 3-10C) (T-cell chemotactic factor) [Cleaved into: MDNCF-a (GCP/IL-8 protein IV) (IL8/NAP1 form I); Interleukin-8 ((Ala-IL-8)77) (GCP/IL-8 protein II) (IL-8(1-77)) (IL8/NAP1 form II) (MDNCF-b); IL-8(5-77); IL-8(6-77) ((Ser-IL-8)72) (GCP/IL-8 protein I) (IL8/NAP1 form III) (Lymphocyte-derived neutrophil-activating factor) (LYNAP) (MDNCF-c) (Neutrophil-activating factor) (NAF); IL-8(7-77) (GCP/IL-8 protein V) (IL8/NAP1 form IV); IL-8(8-77) (GCP/IL-8 protein VI) (IL8/NAP1 form V); IL-8(9-77) (GCP/IL-8 protein III) (IL8/NAP1 form VI)]', 'Homo sapiens', 'chemokine', 'Human immune-related protein annotated in UniProt; class: chemokine.', 'protein', 'MTSKLAVALLAAFLISAALCEGAVLPRSAKELRCQCIKTYSKPFHPKFIKELRVIESGPHCANTEIIVKLSDGRELCLDPKENWVQRVVEKFLKRAENS', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/P10145/entry'),
('CCL2', 'ENSG00000108691', 'P13500', 'C-C motif chemokine 2 (HC11) (Monocyte chemoattractant protein 1) (Monocyte chemotactic and activating factor) (MCAF) (Monocyte chemotactic protein 1) (MCP-1) (Monocyte secretory protein JE) (Small-inducible cytokine A2)', 'Homo sapiens', 'chemokine', 'Human immune-related protein annotated in UniProt; class: chemokine.', 'protein', 'MKVSAALLCLLLIAATFIPQGLAQPDAINAPVTCCYNFTNRKISVQRLASYRRITSSKCPKEAVIFKTIVAKEICADPKQKWVQDSMDHLDKQTQTPKT', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/P13500/entry'),
('TLR2', 'ENSG00000137462', 'O60603', 'Toll-like receptor 2 (Toll/interleukin-1 receptor-like protein 4) (CD antigen CD282)', 'Homo sapiens', 'pattern recognition receptor', 'Human immune-related protein annotated in UniProt; class: pattern recognition receptor.', 'protein', 'MPHTLWMVWVLGVIISLSKEESSNQASLSCDRNGICKGSSGSLNSIPSGLTEAVKSLDLSNNRITYISNSDLQRCVNLQALVLTSNGINTIEEDSFSSLGSLEHLDLSYNYLSNLSSSWFKPLSSLTFLNLLGNPYKTLGETSLFSHLTKLQILRVGNMDTFTKIQRKDFAGLTFLEELEIDASDLQSYEPKSLKSIQNVSHLILHMKQHILLLEIFVDVTSSVECLELRDTDLDTFHFSELSTGETNSLIKKFTFRNVKITDESLFQVMKLLNQISGLLELEFDDCTLNGVGNFRASDNDRVIDPGKVETLTIRRLHIPRFYLFYDLSTLYSLTERVKRITVENSKVFLVPCLLSQHLKSLEYLDLSENLMVEEYLKNSACEDAWPSLQTLILRQNHLASLEKTGETLLTLKNLTNIDISKNSFHSMPETCQWPEKMKYLNLSSTRIHSVTGCIPKTLEILDVSNNNLNLFSLNLPQLKELYISRNKLMTLPDASLLPMLLVLKISRNAITTFSKEQLDSFHTLKTLEAGGNNFICSCEFLSFTQEQQALAKVLIDWPANYLCDSPSHVRGQQVQDVRLSVSECHRTALVSGMCCALFLLILLTGVLCHRFHGLWYMKMMWAWLQAKRKPRKAPSRNICYDAFVSYSERDAYWVENLMVQELENFNPPFKLCLHKRDFIPGKWIIDNIIDSIEKSHKTVFVLSENFVKSEWCKYELDFSHFRLFDENNDAAILILLEPIEKKAIPQRFCKLRKIMNTKTYLEWPMDEAQREGFWVNLRAAIKS', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/O60603/entry'),
('TLR4', 'ENSG00000136869', 'O00206', 'Toll-like receptor 4 (hToll) (CD antigen CD284)', 'Homo sapiens', 'pattern recognition receptor', 'Human immune-related protein annotated in UniProt; class: pattern recognition receptor.', 'protein', 'MMSASRLAGTLIPAMAFLSCVRPESWEPCVEVVPNITYQCMELNFYKIPDNLPFSTKNLDLSFNPLRHLGSYSFFSFPELQVLDLSRCEIQTIEDGAYQSLSHLSTLILTGNPIQSLALGAFSGLSSLQKLVAVETNLASLENFPIGHLKTLKELNVAHNLIQSFKLPEYFSNLTNLEHLDLSSNKIQSIYCTDLRVLHQMPLLNLSLDLSLNPMNFIQPGAFKEIRLHKLTLRNNFDSLNVMKTCIQGLAGLEVHRLVLGEFRNEGNLEKFDKSALEGLCNLTIEEFRLAYLDYYLDDIIDLFNCLTNVSSFSLVSVTIERVKDFSYNFGWQHLELVNCKFGQFPTLKLKSLKRLTFTSNKGGNAFSEVDLPSLEFLDLSRNGLSFKGCCSQSDFGTTSLKYLDLSFNGVITMSSNFLGLEQLEHLDFQHSNLKQMSEFSVFLSLRNLIYLDISHTHTRVAFNGIFNGLSSLEVLKMAGNSFQENFLPDIFTELRNLTFLDLSQCQLEQLSPTAFNSLSSLQVLNMSHNNFFSLDTFPYKCLNSLQVLDYSLNHIMTSKKQELQHFPSSLAFLNLTQNDFACTCEHQSFLQWIKDQRQLLVEVERMECATPSDKQGMPVLSLNITCQMNKTIIGVSVLSVLVVSVVAVLVYKFYFHLMLLAGCIKYGRGENIYDAFVIYSSQDEDWVRNELVKNLEEGVPPFQLCLHYRDFIPGVAIAANIIHEGFHKSRKVIVVVSQHFIQSRWCIFEYEIAQTWQFLSSRAGIIFIVLQKVEKTLLRQQVELYRLLSRNTYLEWEDSVLGRHIFWRRLRKALLDGKSWNPEGTVGTGCNWQEATSI', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/O00206/entry'),
('CD14', 'ENSG00000170458', 'P08571', 'Monocyte differentiation antigen CD14 (My23 antigen) (Myeloid cell-specific leucine-rich glycoprotein) (CD antigen CD14) [Cleaved into: Monocyte differentiation antigen CD14, urinary form; Monocyte differentiation antigen CD14, membrane-bound form]', 'Homo sapiens', 'pattern recognition receptor', 'Human immune-related protein annotated in UniProt; class: pattern recognition receptor.', 'protein', 'MERASCLLLLLLPLVHVSATTPEPCELDDEDFRCVCNFSEPQPDWSEAFQCVSAVEVEIHAGGLNLEPFLKRVDADADPRQYADTVKALRVRRLTVGAAQVPAQLLVGALRVLAYSRLKELTLEDLKITGTMPPLPLEATGLALSSLRLRNVSWATGRSWLAELQQWLKPGLKVLSIAQAHSPAFSCEQVRAFPALTSLDLSDNPGLGERGLMAALCPHKFPAIQNLALRNTGMETPTGVCAALAAAGVQPHSLDLSHNSLRATVNPSAPRCMWSSALNSLNLSFAGLEQVPKGLPAKLRVLDLSCNRLNRAPQPDELPEVDNLTLDGNPFLVPGTALPHEGSMNSGVVPACARSTLSVGVSGTLVLLQGARGFA', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/P08571/entry'),
('MYD88', 'ENSG00000172936', 'Q99836', 'Myeloid differentiation primary response protein MyD88', 'Homo sapiens', 'signaling adaptor', 'Human immune-related protein annotated in UniProt; class: signaling adaptor.', 'protein', 'MAAGGPGAGSAAPVSSTSSLPLAALNMRVRRRLSLFLNVRTQVAADWTALAEEMDFEYLEIRQLETQADPTGRLLDAWQGRPGASVGRLLELLTKLGRDDVLLELGPSIEEDCQKYILKQQQEEAEKPLQVAAVDSSVPRTAELAGITTLDDPLGHMPERFDAFICYCPSDIQFVQEMIRQLEQTNYRLKLCVSDRDVLPGTCVWSIASELIEKRCRRMVVVVSDDYLQSKECDFQTKFALSLSPGAHQKRLIPIKYKAMKKEFPSILRFITVCDYTNPCTKSWFWTRLAKALSLP', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/Q99836/entry'),
('NFKB1', 'ENSG00000109320', 'P19838', 'Nuclear factor NF-kappa-B p105 subunit (DNA-binding factor KBF1) (EBP-1) (Nuclear factor of kappa light polypeptide gene enhancer in B-cells 1) [Cleaved into: Nuclear factor NF-kappa-B p50 subunit]', 'Homo sapiens', 'transcription factor', 'Human immune-related protein annotated in UniProt; class: transcription factor.', 'protein', 'MAEDDPYLGRPEQMFHLDPSLTHTIFNPEVFQPQMALPTDGPYLQILEQPKQRGFRFRYVCEGPSHGGLPGASSEKNKKSYPQVKICNYVGPAKVIVQLVTNGKNIHLHAHSLVGKHCEDGICTVTAGPKDMVVGFANLGILHVTKKKVFETLEARMTEACIRGYNPGLLVHPDLAYLQAEGGGDRQLGDREKELIRQAALQQTKEMDLSVVRLMFTAFLPDSTGSFTRRLEPVVSDAIYDSKAPNASNLKIVRMDRTAGCVTGGEEIYLLCDKVQKDDIQIRFYEEEENGGVWEGFGDFSPTDVHRQFAIVFKTPKYKDINITKPASVFVQLRRKSDLETSEPKPFLYYPEIKDKEEVQRKRQKLMPNFSDSFGGGSGAGAGGGGMFGSGGGGGGTGSTGPGYSFPHYGFPTYGGITFHPGTTKSNAGMKHGTMDTESKKDPEGCDKSDDKNTVNLFGKVIETTEQDQEPSEATVGNGEVTLTYATGTKEESAGVQDNLFLEKAMQLAKRHANALFDYAVTGDVKMLLAVQRHLTAVQDENGDSVLHLAIIHLHSQLVRDLLEVTSGLISDDIINMRNDLYQTPLHLAVITKQEDVVEDLLRAGADLSLLDRLGNSVLHLAAKEGHDKVLSILLKHKKAALLLDHPNGDGLNAIHLAMMSNSLPCLLLLVAAGADVNAQEQKSGRTALHLAVEHDNISLAGCLLLEGDAHVDSTTYDGTTPLHIAAGRGSTRLAALLKAAGADPLVENFEPLYDLDDSWENAGEDEGVVPGTTPLDMATSWQVFDILNGKPYEPEFTSDDLLAQGDMKQLAEDVKLQLYKLLEIPDPDKNWATLAQKLGLGILNNAFRLSPAPSKTLMDNYEVSGGTVRELVEALRQMGYTEAIEVIQAASSPVKTTSQAHSLPLSPASTRQQIDELRDSDSVCDSGVETSFRKLSFTESLTSGASLLTLNKMPHDYGQEGPLEGKI', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/P19838/entry'),
('RELA', 'ENSG00000173039', 'Q04206', 'Transcription factor p65 (Nuclear factor NF-kappa-B p65 subunit) (Nuclear factor of kappa light polypeptide gene enhancer in B-cells 3)', 'Homo sapiens', 'transcription factor', 'Human immune-related protein annotated in UniProt; class: transcription factor.', 'protein', 'MDELFPLIFPAEPAQASGPYVEIIEQPKQRGMRFRYKCEGRSAGSIPGERSTDTTKTHPTIKINGYTGPGTVRISLVTKDPPHRPHPHELVGKDCRDGFYEAELCPDRCIHSFQNLGIQCVKKRDLEQAISQRIQTNNNPFQVPIEEQRGDYDLNAVRLCFQVTVRDPSGRPLRLPPVLSHPIFDNRAPNTAELKICRVNRNSGSCLGGDEIFLLCDKVQKEDIEVYFTGPGWEARGSFSQADVHRQVAIVFRTPPYADPSLQAPVRVSMQLRRPSDRELSEPMEFQYLPDTDDRHRIEEKRKRTYETFKSIMKKSPFSGPTDPRPPPRRIAVPSRSSASVPKPAPQPYPFTSSLSTINYDEFPTMVFPSGQISQASALAPAPPQVLPQAPAPAPAPAMVSALAQAPAPVPVLAPGPPQAVAPPAPKPTQAGEGTLSEALLQLQFDDEDLGALLGNSTDPAVFTDLASVDNSEFQQLLNQGIPVAPHTTEPMLMEYPEAITRLVTGAQRPPDPAPAPLGAPGLPNGLLSGDEDFSSIADMDFSALLSQISS', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/Q04206/entry'),
('STAT1', 'ENSG00000115415', 'P42224', 'Signal transducer and activator of transcription 1-alpha/beta (Transcription factor ISGF-3 components p91/p84)', 'Homo sapiens', 'transcription factor', 'Human immune-related protein annotated in UniProt; class: transcription factor.', 'protein', 'MSQWYELQQLDSKFLEQVHQLYDDSFPMEIRQYLAQWLEKQDWEHAANDVSFATIRFHDLLSQLDDQYSRFSLENNFLLQHNIRKSKRNLQDNFQEDPIQMSMIIYSCLKEERKILENAQRFNQAQSGNIQSTVMLDKQKELDSKVRNVKDKVMCIEHEIKSLEDLQDEYDFKCKTLQNREHETNGVAKSDQKQEQLLLKKMYLMLDNKRKEVVHKIIELLNVTELTQNALINDELVEWKRRQQSACIGGPPNACLDQLQNWFTIVAESLQQVRQQLKKLEELEQKYTYEHDPITKNKQVLWDRTFSLFQQLIQSSFVVERQPCMPTHPQRPLVLKTGVQFTVKLRLLVKLQELNYNLKVKVLFDKDVNERNTVKGFRKFNILGTHTKVMNMEESTNGSLAAEFRHLQLKEQKNAGTRTNEGPLIVTEELHSLSFETQLCQPGLVIDLETTSLPVVVISNVSQLPSGWASILWYNMLVAEPRNLSFFLTPPCARWAQLSEVLSWQFSSVTKRGLNVDQLNMLGEKLLGPNASPDGLIPWTRFCKENINDKNFPFWLWIESILELIKKHLLPLWNDGCIMGFISKERERALLKDQQPGTFLLRFSESSREGAITFTWVERSQNGGEPDFHAVEPYTKKELSAVTFPDIIRNYKVMAAENIPENPLKYLYPNIDKDHAFGKYYSRPKEAPEPMELDGPKGTGYIKTELISVSEVHPSRLQTTDNLLPMSPEEFDEVSRIVGSVEFDSMMNTV', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/P42224/entry'),
('STAT3', 'ENSG00000168610', 'P40763', 'Signal transducer and activator of transcription 3 (Acute-phase response factor)', 'Homo sapiens', 'transcription factor', 'Human immune-related protein annotated in UniProt; class: transcription factor.', 'protein', 'MAQWNQLQQLDTRYLEQLHQLYSDSFPMELRQFLAPWIESQDWAYAASKESHATLVFHNLLGEIDQQYSRFLQESNVLYQHNLRRIKQFLQSRYLEKPMEIARIVARCLWEESRLLQTAATAAQQGGQANHPTAAVVTEKQQMLEQHLQDVRKRVQDLEQKMKVVENLQDDFDFNYKTLKSQGDMQDLNGNNQSVTRQKMQQLEQMLTALDQMRRSIVSELAGLLSAMEYVQKTLTDEELADWKRRQQIACIGGPPNICLDRLENWITSLAESQLQTRQQIKKLEELQQKVSYKGDPIVQHRPMLEERIVELFRNLMKSAFVVERQPCMPMHPDRPLVIKTGVQFTTKVRLLVKFPELNYQLKIKVCIDKDSGDVAALRGSRKFNILGTNTKVMNMEESNNGSLSAEFKHLTLREQRCGNGGRANCDASLIVTEELHLITFETEVYHQGLKIDLETHSLPVVVISNICQMPNAWASILWYNMLTNNPKNVNFFTKPPIGTWDQVAEVLSWQFSSTTKRGLSIEQLTTLAEKLLGPGVNYSGCQITWAKFCKENMAGKGFSFWVWLDNIIDLVKKYILALWNEGYIMGFISKERERAILSTKPPGTFLLRFSESSKEGGVTFTWVEKDISGKTQIQSVEPYTKQQLNNMSFAEIIMGYKIMDATNILVSPLVYLYPDIPKEEAFGKYCRPESQEHPEADPGSAAPYLKTKFICVTPTTCSNTIDLPMSPRTLDSLMQFGNNGEGAEPSAGGQFESLTFDMELTSECATSPM', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/P40763/entry'),
('JAK1', 'ENSG00000162434', 'P23458', 'Tyrosine-protein kinase JAK1 (EC 2.7.10.2) (Janus kinase 1) (JAK-1)', 'Homo sapiens', 'kinase', 'Human immune-related protein annotated in UniProt; class: kinase.', 'protein', 'MQYLNIKEDCNAMAFCAKMRSSKKTEVNLEAPEPGVEVIFYLSDREPLRLGSGEYTAEELCIRAAQACRISPLCHNLFALYDENTKLWYAPNRTITVDDKMSLRLHYRMRFYFTNWHGTNDNEQSVWRHSPKKQKNGYEKKKIPDATPLLDASSLEYLFAQGQYDLVKCLAPIRDPKTEQDGHDIENECLGMAVLAISHYAMMKKMQLPELPKDISYKRYIPETLNKSIRQRNLLTRMRINNVFKDFLKEFNNKTICDSSVSTHDLKVKYLATLETLTKHYGAEIFETSMLLISSENEMNWFHSNDGGNVLYYEVMVTGNLGIQWRHKPNVVSVEKEKNKLKRKKLENKHKKDEEKNKIREEWNNFSYFPEITHIVIKESVVSINKQDNKKMELKLSSHEEALSFVSLVDGYFRLTADAHHYLCTDVAPPLIVHNIQNGCHGPICTEYAINKLRQEGSEEGMYVLRWSCTDFDNILMTVTCFEKSEQVQGAQKQFKNFQIEVQKGRYSLHGSDRSFPSLGDLMSHLKKQILRTDNISFMLKRCCQPKPREISNLLVATKKAQEWQPVYPMSQLSFDRILKKDLVQGEHLGRGTRTHIYSGTLMDYKDDEGTSEEKKIKVILKVLDPSHRDISLAFFEAASMMRQVSHKHIVYLYGVCVRDVENIMVEEFVEGGPLDLFMHRKSDVLTTPWKFKVAKQLASALSYLEDKDLVHGNVCTKNLLLAREGIDSECGPFIKLSDPGIPITVLSRQECIERIPWIAPECVEDSKNLSVAADKWSFGTTLWEICYNGEIPLKDKTLIEKERFYESRCRPVTPSCKELADLMTRCMNYDPNQRPFFRAIMRDINKLEEQNPDIVSEKKPATEVDPTHFEKRFLKRIRDLGEGHFGKVELCRYDPEGDNTGEQVAVKSLKPESGGNHIADLKKEIEILRNLYHENIVKYKGICTEDGGNGIKLIMEFLPSGSLKEYLPKNKNKINLKQQLKYAVQICKGMDYLGSRQYVHRDLAARNVLVESEHQVKIGDFGLTKAIETDKEYYTVKDDRDSPVFWYAPECLMQSKFYIASDVWSFGVTLHELLTYCDSDSSPMALFLKMIGPTHGQMTVTRLVNTLKEGKRLPCPPNCPDEVYQLMRKCWEFQPSNRTSFQNLIEGFEALLK', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/P23458/entry'),
('JAK2', 'ENSG00000096968', 'O60674', 'Tyrosine-protein kinase JAK2 (EC 2.7.10.2) (Janus kinase 2) (JAK-2)', 'Homo sapiens', 'kinase', 'Human immune-related protein annotated in UniProt; class: kinase.', 'protein', 'MGMACLTMTEMEGTSTSSIYQNGDISGNANSMKQIDPVLQVYLYHSLGKSEADYLTFPSGEYVAEEICIAASKACGITPVYHNMFALMSETERIWYPPNHVFHIDESTRHNVLYRIRFYFPRWYCSGSNRAYRHGISRGAEAPLLDDFVMSYLFAQWRHDFVHGWIKVPVTHETQEECLGMAVLDMMRIAKENDQTPLAIYNSISYKTFLPKCIRAKIQDYHILTRKRIRYRFRRFIQQFSQCKATARNLKLKYLINLETLQSAFYTEKFEVKEPGSGPSGEEIFATIIITGNGGIQWSRGKHKESETLTEQDLQLYCDFPNIIDVSIKQANQEGSNESRVVTIHKQDGKNLEIELSSLREALSFVSLIDGYYRLTADAHHYLCKEVAPPAVLENIQSNCHGPISMDFAISKLKKAGNQTGLYVLRCSPKDFNKYFLTFAVERENVIEYKHCLITKNENEEYNLSGTKKNFSSLKDLLNCYQMETVRSDNIIFQFTKCCPPKPKDKSNLLVFRTNGVSDVPTSPTLQRPTHMNQMVFHKIRNEDLIFNESLGQGTFTKIFKGVRREVGDYGQLHETEVLLKVLDKAHRNYSESFFEAASMMSKLSHKHLVLNYGVCVCGDENILVQEFVKFGSLDTYLKKNKNCINILWKLEVAKQLAWAMHFLEENTLIHGNVCAKNILLIREEDRKTGNPPFIKLSDPGISITVLPKDILQERIPWVPPECIENPKNLNLATDKWSFGTTLWEICSGGDKPLSALDSQRKLQFYEDRHQLPAPKWAELANLINNCMDYEPDFRPSFRAIIRDLNSLFTPDYELLTENDMLPNMRIGALGFSGAFEDRDPTQFEERHLKFLQQLGKGNFGSVEMCRYDPLQDNTGEVVAVKKLQHSTEEHLRDFEREIEILKSLQHDNIVKYKGVCYSAGRRNLKLIMEYLPYGSLRDYLQKHKERIDHIKLLQYTSQICKGMEYLGTKRYIHRDLATRNILVENENRVKIGDFGLTKVLPQDKEYYKVKEPGESPIFWYAPESLTESKFSVASDVWSFGVVLYELFTYIEKSKSPPAEFMRMIGNDKQGQMIVFHLIELLKNNGRLPRPDGCPDEIYMIMTECWNNNVNQRPSFRDLALRVDQIRDNMAG', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/O60674/entry'),
('IRF3', 'ENSG00000126456', 'Q14653', 'Interferon regulatory factor 3 (IRF-3)', 'Homo sapiens', 'transcription factor', 'Human immune-related protein annotated in UniProt; class: transcription factor.', 'protein', 'MGTPKPRILPWLVSQLDLGQLEGVAWVNKSRTRFRIPWKHGLRQDAQQEDFGIFQAWAEATGAYVPGRDKPDLPTWKRNFRSALNRKEGLRLAEDRSKDPHDPHKIYEFVNSGVGDFSQPDTSPDTNGGGSTSDTQEDILDELLGNMVLAPLPDPGPPSLAVAPEPCPQPLRSPSLDNPTPFPNLGPSENPLKRLLVPGEEWEFEVTAFYRGRQVFQQTISCPEGLRLVGSEVGDRTLPGWPVTLPDPGMSLTDRGVMSYVRHVLSCLGGGLALWRAGQWLWAQRLGHCHTYWAVSEELLPNSGHGPDGEVPKDKEGGVFDLGPFIVDLITFTEGSGRSPRYALWFCVGESWPQDQPWTKRLVMVKVVPTCLRALVEMARVGGASSLENTVDLHISNSHPLSLTSDQYKAYLQDLVEGMDFQGPGES', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/Q14653/entry'),
('IRF7', 'ENSG00000185507', 'Q92985', 'Interferon regulatory factor 7 (IRF-7)', 'Homo sapiens', 'transcription factor', 'Human immune-related protein annotated in UniProt; class: transcription factor.', 'protein', 'MALAPERAAPRVLFGEWLLGEISSGCYEGLQWLDEARTCFRVPWKHFARKDLSEADARIFKAWAVARGRWPPSSRGGGPPPEAETAERAGWKTNFRCALRSTRRFVMLRDNSGDPADPHKVYALSRELCWREGPGTDQTEAEAPAAVPPPQGGPPGPFLAHTHAGLQAPGPLPAPAGDKGDLLLQAVQQSCLADHLLTASWGADPVPTKAPGEGQEGLPLTGACAGGPGLPAGELYGWAVETTPSPGPQPAALTTGEAAAPESPHQAEPYLSPSPSACTAVQEPSPGALDVTIMYKGRTVLQKVVGHPSCTFLYGPPDPAVRATDPQQVAFPSPAELPDQKQLRYTEELLRHVAPGLHLELRGPQLWARRMGKCKVYWEVGGPPGSASPSTPACLLPRNCDTPIFDFRVFFQELVEFRARQRRGSPRYTIYLGFGQDLSAGRPKEKSLVLVKLEPWLCRVHLEGTQREGVSSLDSSSLSLCLSSANSLYDDIECFLMELEQPA', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/Q92985/entry'),
('HLA-DRA', 'ENSG00000204287', 'P01903', 'HLA class II histocompatibility antigen, DR alpha chain (MHC class II antigen DRA)', 'Homo sapiens', 'antigen presentation', 'Human immune-related protein annotated in UniProt; class: antigen presentation.', 'protein', 'MAISGVPVLGFFIIAVLMSAQESWAIKEEHVIIQAEFYLNPDQSGEFMFDFDGDEIFHVDMAKKETVWRLEEFGRFASFEAQGALANIAVDKANLEIMTKRSNYTPITNVPPEVTVLTNSPVELREPNVLICFIDKFTPPVVNVTWLRNGKPVTTGVSETVFLPREDHLFRKFHYLPFLPSTEDVYDCRVEHWGLDEPLLKHWEFDAPSPLPETTENVVCALGLTVGLVGIIIGTIFIIKGLRKSNAAERRGPL', 'UniProt;Human Protein Atlas', 'https://www.uniprot.org/uniprotkb/P01903/entry');

INSERT INTO samples (sample_name, tissue, condition_name, species, source_database, description) VALUES
('MAIT T-cell', 'MAIT T-cell', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('NK-cell', 'NK-cell', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('T-reg', 'T-reg', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('basophil', 'basophil', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('classical monocyte', 'classical monocyte', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('eosinophil', 'eosinophil', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('gdT-cell', 'gdT-cell', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('intermediate monocyte', 'intermediate monocyte', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('memory B-cell', 'memory B-cell', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('memory CD4 T-cell', 'memory CD4 T-cell', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('memory CD8 T-cell', 'memory CD8 T-cell', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('myeloid DC', 'myeloid DC', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('naive B-cell', 'naive B-cell', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('naive CD4 T-cell', 'naive CD4 T-cell', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('naive CD8 T-cell', 'naive CD8 T-cell', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('neutrophil', 'neutrophil', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('non-classical monocyte', 'non-classical monocyte', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('plasmacytoid DC', 'plasmacytoid DC', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample'),
('total PBMC', 'total PBMC', 'normal immune cell', 'Homo sapiens', 'Human Protein Atlas', 'HPA immune cell RNA expression summary sample');

INSERT INTO expression (gene_id, sample_id, expression_value, expression_unit) VALUES
(1, 1, 0.0, 'TPM'),
(1, 2, 0.0, 'TPM'),
(1, 3, 0.0, 'TPM'),
(1, 4, 0.0, 'TPM'),
(1, 5, 0.0, 'TPM'),
(1, 6, 0.0, 'TPM'),
(1, 7, 0.0, 'TPM'),
(1, 8, 0.0, 'TPM'),
(1, 9, 2.7, 'TPM'),
(1, 10, 0.0, 'TPM'),
(1, 11, 0.0, 'TPM'),
(1, 12, 0.0, 'TPM'),
(1, 13, 3.9, 'TPM'),
(1, 14, 0.0, 'TPM'),
(1, 15, 0.0, 'TPM'),
(1, 16, 0.0, 'TPM'),
(1, 17, 0.0, 'TPM'),
(1, 18, 0.0, 'TPM'),
(1, 19, 0.0, 'TPM'),
(2, 1, 0.0, 'TPM'),
(2, 2, 0.2, 'TPM'),
(2, 3, 0.0, 'TPM'),
(2, 4, 1.6, 'TPM'),
(2, 5, 9.4, 'TPM'),
(2, 6, 3.5, 'TPM'),
(2, 7, 0.0, 'TPM'),
(2, 8, 15.8, 'TPM'),
(2, 9, 0.0, 'TPM'),
(2, 10, 0.0, 'TPM'),
(2, 11, 0.0, 'TPM'),
(2, 12, 16.5, 'TPM'),
(2, 13, 0.0, 'TPM'),
(2, 14, 0.0, 'TPM'),
(2, 15, 0.0, 'TPM'),
(2, 16, 61.5, 'TPM'),
(2, 17, 6.3, 'TPM'),
(2, 18, 0.0, 'TPM'),
(2, 19, 1.3, 'TPM'),
(3, 1, 40.3, 'TPM'),
(3, 2, 2.9, 'TPM'),
(3, 3, 13.3, 'TPM'),
(3, 4, 0.0, 'TPM'),
(3, 5, 8.6, 'TPM'),
(3, 6, 0.0, 'TPM'),
(3, 7, 27.6, 'TPM'),
(3, 8, 33.7, 'TPM'),
(3, 9, 5.7, 'TPM'),
(3, 10, 18.1, 'TPM'),
(3, 11, 15.1, 'TPM'),
(3, 12, 6.9, 'TPM'),
(3, 13, 6.5, 'TPM'),
(3, 14, 5.0, 'TPM'),
(3, 15, 6.1, 'TPM'),
(3, 16, 14.3, 'TPM'),
(3, 17, 60.1, 'TPM'),
(3, 18, 4.4, 'TPM'),
(3, 19, 6.7, 'TPM'),
(4, 1, 0.0, 'TPM'),
(4, 2, 1.1, 'TPM'),
(4, 3, 0.1, 'TPM'),
(4, 4, 0.0, 'TPM'),
(4, 5, 0.0, 'TPM'),
(4, 6, 0.0, 'TPM'),
(4, 7, 6.0, 'TPM'),
(4, 8, 0.0, 'TPM'),
(4, 9, 0.0, 'TPM'),
(4, 10, 2.3, 'TPM'),
(4, 11, 6.6, 'TPM'),
(4, 12, 0.0, 'TPM'),
(4, 13, 0.3, 'TPM'),
(4, 14, 0.5, 'TPM'),
(4, 15, 3.7, 'TPM'),
(4, 16, 0.1, 'TPM'),
(4, 17, 0.0, 'TPM'),
(4, 18, 0.0, 'TPM'),
(4, 19, 0.4, 'TPM'),
(5, 1, 0.0, 'TPM'),
(5, 2, 0.0, 'TPM'),
(5, 3, 0.3, 'TPM'),
(5, 4, 0.0, 'TPM'),
(5, 5, 1.4, 'TPM'),
(5, 6, 0.0, 'TPM'),
(5, 7, 0.0, 'TPM'),
(5, 8, 1.0, 'TPM'),
(5, 9, 0.0, 'TPM'),
(5, 10, 0.0, 'TPM'),
(5, 11, 0.2, 'TPM'),
(5, 12, 0.1, 'TPM'),
(5, 13, 0.0, 'TPM'),
(5, 14, 0.0, 'TPM'),
(5, 15, 0.0, 'TPM'),
(5, 16, 0.0, 'TPM'),
(5, 17, 0.4, 'TPM'),
(5, 18, 0.0, 'TPM'),
(5, 19, 0.1, 'TPM'),
(6, 1, 0.0, 'TPM'),
(6, 2, 0.0, 'TPM'),
(6, 3, 0.0, 'TPM'),
(6, 4, 0.9, 'TPM'),
(6, 5, 0.3, 'TPM'),
(6, 6, 0.1, 'TPM'),
(6, 7, 0.0, 'TPM'),
(6, 8, 0.1, 'TPM'),
(6, 9, 0.0, 'TPM'),
(6, 10, 0.0, 'TPM'),
(6, 11, 0.0, 'TPM'),
(6, 12, 0.0, 'TPM'),
(6, 13, 0.0, 'TPM'),
(6, 14, 0.0, 'TPM'),
(6, 15, 0.0, 'TPM'),
(6, 16, 273.1, 'TPM'),
(6, 17, 0.0, 'TPM'),
(6, 18, 0.0, 'TPM'),
(6, 19, 0.0, 'TPM'),
(7, 1, 0.0, 'TPM'),
(7, 2, 0.0, 'TPM'),
(7, 3, 0.0, 'TPM'),
(7, 4, 0.0, 'TPM'),
(7, 5, 6.3, 'TPM'),
(7, 6, 2.6, 'TPM'),
(7, 7, 0.0, 'TPM'),
(7, 8, 0.2, 'TPM'),
(7, 9, 0.0, 'TPM'),
(7, 10, 0.0, 'TPM'),
(7, 11, 0.0, 'TPM'),
(7, 12, 0.7, 'TPM'),
(7, 13, 0.0, 'TPM'),
(7, 14, 0.0, 'TPM'),
(7, 15, 0.0, 'TPM'),
(7, 16, 0.3, 'TPM'),
(7, 17, 0.0, 'TPM'),
(7, 18, 0.2, 'TPM'),
(7, 19, 0.8, 'TPM'),
(8, 1, 0.4, 'TPM'),
(8, 2, 6.0, 'TPM'),
(8, 3, 0.1, 'TPM'),
(8, 4, 35.5, 'TPM'),
(8, 5, 149.9, 'TPM'),
(8, 6, 1.4, 'TPM'),
(8, 7, 0.3, 'TPM'),
(8, 8, 147.6, 'TPM'),
(8, 9, 0.3, 'TPM'),
(8, 10, 0.9, 'TPM'),
(8, 11, 0.3, 'TPM'),
(8, 12, 103.4, 'TPM'),
(8, 13, 1.0, 'TPM'),
(8, 14, 1.1, 'TPM'),
(8, 15, 0.2, 'TPM'),
(8, 16, 294.0, 'TPM'),
(8, 17, 100.2, 'TPM'),
(8, 18, 1.1, 'TPM'),
(8, 19, 27.7, 'TPM'),
(9, 1, 0.0, 'TPM'),
(9, 2, 0.1, 'TPM'),
(9, 3, 0.0, 'TPM'),
(9, 4, 46.8, 'TPM'),
(9, 5, 50.3, 'TPM'),
(9, 6, 17.9, 'TPM'),
(9, 7, 0.1, 'TPM'),
(9, 8, 47.7, 'TPM'),
(9, 9, 1.2, 'TPM'),
(9, 10, 0.0, 'TPM'),
(9, 11, 0.0, 'TPM'),
(9, 12, 18.9, 'TPM'),
(9, 13, 0.4, 'TPM'),
(9, 14, 0.0, 'TPM'),
(9, 15, 0.0, 'TPM'),
(9, 16, 55.5, 'TPM'),
(9, 17, 52.2, 'TPM'),
(9, 18, 0.8, 'TPM'),
(9, 19, 9.7, 'TPM'),
(10, 1, 7.4, 'TPM'),
(10, 2, 3.8, 'TPM'),
(10, 3, 2.8, 'TPM'),
(10, 4, 7.5, 'TPM'),
(10, 5, 2598.2, 'TPM'),
(10, 6, 15.2, 'TPM'),
(10, 7, 6.1, 'TPM'),
(10, 8, 509.1, 'TPM'),
(10, 9, 5.7, 'TPM'),
(10, 10, 3.1, 'TPM'),
(10, 11, 3.4, 'TPM'),
(10, 12, 338.4, 'TPM'),
(10, 13, 1.3, 'TPM'),
(10, 14, 4.3, 'TPM'),
(10, 15, 2.7, 'TPM'),
(10, 16, 585.0, 'TPM'),
(10, 17, 72.8, 'TPM'),
(10, 18, 21.9, 'TPM'),
(10, 19, 1005.0, 'TPM'),
(11, 1, 57.2, 'TPM'),
(11, 2, 56.8, 'TPM'),
(11, 3, 75.3, 'TPM'),
(11, 4, 216.0, 'TPM'),
(11, 5, 175.8, 'TPM'),
(11, 6, 241.3, 'TPM'),
(11, 7, 72.1, 'TPM'),
(11, 8, 269.1, 'TPM'),
(11, 9, 30.7, 'TPM'),
(11, 10, 56.5, 'TPM'),
(11, 11, 68.9, 'TPM'),
(11, 12, 174.4, 'TPM'),
(11, 13, 28.3, 'TPM'),
(11, 14, 38.0, 'TPM'),
(11, 15, 56.6, 'TPM'),
(11, 16, 183.2, 'TPM'),
(11, 17, 352.9, 'TPM'),
(11, 18, 92.0, 'TPM'),
(11, 19, 93.5, 'TPM'),
(12, 1, 0.7, 'TPM'),
(12, 2, 1.6, 'TPM'),
(12, 3, 0.2, 'TPM'),
(12, 4, 0.0, 'TPM'),
(12, 5, 0.7, 'TPM'),
(12, 6, 0.9, 'TPM'),
(12, 7, 0.5, 'TPM'),
(12, 8, 1.4, 'TPM'),
(12, 9, 0.4, 'TPM'),
(12, 10, 1.4, 'TPM'),
(12, 11, 0.9, 'TPM'),
(12, 12, 2.1, 'TPM'),
(12, 13, 0.4, 'TPM'),
(12, 14, 2.0, 'TPM'),
(12, 15, 0.9, 'TPM'),
(12, 16, 0.4, 'TPM'),
(12, 17, 1.8, 'TPM'),
(12, 18, 0.3, 'TPM'),
(12, 19, 0.3, 'TPM'),
(13, 1, 25.4, 'TPM'),
(13, 2, 27.9, 'TPM'),
(13, 3, 18.5, 'TPM'),
(13, 4, 11.5, 'TPM'),
(13, 5, 10.6, 'TPM'),
(13, 6, 14.9, 'TPM'),
(13, 7, 24.3, 'TPM'),
(13, 8, 14.0, 'TPM'),
(13, 9, 11.7, 'TPM'),
(13, 10, 18.3, 'TPM'),
(13, 11, 22.2, 'TPM'),
(13, 12, 13.1, 'TPM'),
(13, 13, 11.8, 'TPM'),
(13, 14, 16.6, 'TPM'),
(13, 15, 18.7, 'TPM'),
(13, 16, 13.5, 'TPM'),
(13, 17, 12.9, 'TPM'),
(13, 18, 14.1, 'TPM'),
(13, 19, 6.8, 'TPM'),
(14, 1, 71.6, 'TPM'),
(14, 2, 87.9, 'TPM'),
(14, 3, 196.6, 'TPM'),
(14, 4, 43.0, 'TPM'),
(14, 5, 114.0, 'TPM'),
(14, 6, 87.2, 'TPM'),
(14, 7, 56.0, 'TPM'),
(14, 8, 159.2, 'TPM'),
(14, 9, 26.7, 'TPM'),
(14, 10, 122.8, 'TPM'),
(14, 11, 79.2, 'TPM'),
(14, 12, 52.2, 'TPM'),
(14, 13, 23.5, 'TPM'),
(14, 14, 116.6, 'TPM'),
(14, 15, 89.8, 'TPM'),
(14, 16, 130.9, 'TPM'),
(14, 17, 94.1, 'TPM'),
(14, 18, 26.5, 'TPM'),
(14, 19, 80.0, 'TPM'),
(15, 1, 62.6, 'TPM'),
(15, 2, 60.4, 'TPM'),
(15, 3, 40.9, 'TPM'),
(15, 4, 94.0, 'TPM'),
(15, 5, 60.8, 'TPM'),
(15, 6, 82.1, 'TPM'),
(15, 7, 84.8, 'TPM'),
(15, 8, 65.7, 'TPM'),
(15, 9, 28.1, 'TPM'),
(15, 10, 53.5, 'TPM'),
(15, 11, 61.7, 'TPM'),
(15, 12, 46.1, 'TPM'),
(15, 13, 29.2, 'TPM'),
(15, 14, 52.6, 'TPM'),
(15, 15, 53.7, 'TPM'),
(15, 16, 166.2, 'TPM'),
(15, 17, 64.5, 'TPM'),
(15, 18, 26.5, 'TPM'),
(15, 19, 49.4, 'TPM'),
(16, 1, 96.0, 'TPM'),
(16, 2, 277.7, 'TPM'),
(16, 3, 92.1, 'TPM'),
(16, 4, 110.0, 'TPM'),
(16, 5, 34.2, 'TPM'),
(16, 6, 107.9, 'TPM'),
(16, 7, 88.1, 'TPM'),
(16, 8, 46.9, 'TPM'),
(16, 9, 55.9, 'TPM'),
(16, 10, 72.4, 'TPM'),
(16, 11, 91.1, 'TPM'),
(16, 12, 50.9, 'TPM'),
(16, 13, 49.1, 'TPM'),
(16, 14, 74.9, 'TPM'),
(16, 15, 67.7, 'TPM'),
(16, 16, 97.9, 'TPM'),
(16, 17, 57.7, 'TPM'),
(16, 18, 43.4, 'TPM'),
(16, 19, 46.6, 'TPM'),
(17, 1, 4.4, 'TPM'),
(17, 2, 10.4, 'TPM'),
(17, 3, 3.9, 'TPM'),
(17, 4, 103.3, 'TPM'),
(17, 5, 16.6, 'TPM'),
(17, 6, 31.0, 'TPM'),
(17, 7, 5.9, 'TPM'),
(17, 8, 16.6, 'TPM'),
(17, 9, 3.8, 'TPM'),
(17, 10, 3.9, 'TPM'),
(17, 11, 3.1, 'TPM'),
(17, 12, 22.4, 'TPM'),
(17, 13, 3.8, 'TPM'),
(17, 14, 2.0, 'TPM'),
(17, 15, 2.7, 'TPM'),
(17, 16, 12.4, 'TPM'),
(17, 17, 13.7, 'TPM'),
(17, 18, 9.0, 'TPM'),
(17, 19, 3.2, 'TPM'),
(18, 1, 51.1, 'TPM'),
(18, 2, 49.4, 'TPM'),
(18, 3, 68.5, 'TPM'),
(18, 4, 18.3, 'TPM'),
(18, 5, 22.5, 'TPM'),
(18, 6, 41.0, 'TPM'),
(18, 7, 62.4, 'TPM'),
(18, 8, 23.2, 'TPM'),
(18, 9, 25.9, 'TPM'),
(18, 10, 52.7, 'TPM'),
(18, 11, 54.5, 'TPM'),
(18, 12, 18.7, 'TPM'),
(18, 13, 26.3, 'TPM'),
(18, 14, 44.3, 'TPM'),
(18, 15, 43.0, 'TPM'),
(18, 16, 22.6, 'TPM'),
(18, 17, 28.7, 'TPM'),
(18, 18, 27.5, 'TPM'),
(18, 19, 18.0, 'TPM'),
(19, 1, 8.0, 'TPM'),
(19, 2, 20.7, 'TPM'),
(19, 3, 11.4, 'TPM'),
(19, 4, 9.6, 'TPM'),
(19, 5, 16.4, 'TPM'),
(19, 6, 24.7, 'TPM'),
(19, 7, 9.2, 'TPM'),
(19, 8, 39.2, 'TPM'),
(19, 9, 11.9, 'TPM'),
(19, 10, 6.3, 'TPM'),
(19, 11, 6.9, 'TPM'),
(19, 12, 20.5, 'TPM'),
(19, 13, 13.3, 'TPM'),
(19, 14, 6.7, 'TPM'),
(19, 15, 7.9, 'TPM'),
(19, 16, 9.0, 'TPM'),
(19, 17, 40.0, 'TPM'),
(19, 18, 551.4, 'TPM'),
(19, 19, 6.8, 'TPM'),
(20, 1, 1.0, 'TPM'),
(20, 2, 14.6, 'TPM'),
(20, 3, 17.1, 'TPM'),
(20, 4, 5.1, 'TPM'),
(20, 5, 175.1, 'TPM'),
(20, 6, 56.1, 'TPM'),
(20, 7, 2.3, 'TPM'),
(20, 8, 278.1, 'TPM'),
(20, 9, 278.6, 'TPM'),
(20, 10, 2.3, 'TPM'),
(20, 11, 11.2, 'TPM'),
(20, 12, 3.9, 'TPM'),
(20, 13, 323.4, 'TPM'),
(20, 14, 1.1, 'TPM'),
(20, 15, 2.3, 'TPM'),
(20, 16, 9.8, 'TPM'),
(20, 17, 178.5, 'TPM'),
(20, 18, 192.9, 'TPM'),
(20, 19, 99.7, 'TPM');

INSERT INTO import_logs (file_name, import_type, records_inserted, notes) VALUES
('genes.csv', 'seed_genes', 20, 'Real gene metadata and protein sequences from UniProt; target IDs mapped in target_genes.tsv'),
('expression.csv', 'seed_expression', 380, 'Human Protein Atlas immune-cell RNA expression TPM records');

CREATE VIEW view_dataset_counts AS
SELECT 'genes' AS table_name, COUNT(*) AS record_count FROM genes
UNION ALL
SELECT 'samples' AS table_name, COUNT(*) AS record_count FROM samples
UNION ALL
SELECT 'expression' AS table_name, COUNT(*) AS record_count FROM expression;

CREATE VIEW view_species_summary AS
SELECT species, COUNT(*) AS gene_count
FROM genes
GROUP BY species
ORDER BY species;

CREATE VIEW view_gene_class_summary AS
SELECT gene_class, COUNT(*) AS gene_count
FROM genes
GROUP BY gene_class
ORDER BY gene_count DESC, gene_class;

CREATE VIEW view_source_summary AS
SELECT source_database, COUNT(*) AS gene_count
FROM genes
GROUP BY source_database
ORDER BY gene_count DESC, source_database;
